- alias: "Media player paused/stopped"
  trigger:
    - platform: state
      entity_id: media_player.white
      from: 'playing'
      to: 'idle'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.standard

- alias: "Media player playing"
  trigger:
    - platform: state
      entity_id: media_player.white
      from: 'idle'
      to: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.movie

- alias: "Show media on CellWall"
  trigger:
    - platform: state
      entity_id: media_player.spotify
      from: 'idle'
      to: 'playing'
  action:
    service: rest_command.cellwall_text
    data_template:
      text: '["{{ states.media_player.spotify.attributes.media_title }}"]'
