- alias: Set TV input via select
  trigger:
    platform: state
    entity_id: input_select.tv_input
  action:
    service: hdmi_cec.select_device
    data_template:
      device: "{{ states('input_select.tv_input') }}"

- alias: Turn on TV via switch
  trigger:
    platform: state
    entity_id: input_boolean.tv_input
    to: 'on'
  action:
    service: hdmi_cec.power_on

- alias: Turn off TV via switch
  trigger:
    platform: state
    entity_id: input_boolean.tv_input
    to: 'off'
  action:
    service: hdmi_cec.standby

- alias: Update switch when TV is on
  trigger:
    platform: state
    entity_id: switch.hdmi_0
    to: 'on'
  action:
    service: input_boolean.turn_on

- alias: Update switch when TV is off
  trigger:
    platform: state
    entity_id: switch.hdmi_0
    to: 'off'
  action:
    service: input_boolean.turn_off
