homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  unit_system: metric
  time_zone: America/Vancouver
  customize: !include customize.yaml

http:
  api_password: !secret http_password
  base_url: https://tiger-home.duckdns.org
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

frontend:

config:

updater:

discovery:

conversation:

recorder:

history:

logbook:

sun:

cloud:

sensor:
  - platform: yr
    name: Weather
    monitored_conditions:
      - symbol
      - temperature
      - windSpeed
      - cloudiness
  - platform: google_travel_time
    api_key: !secret google_api
    origin: !secret coordinates
    destination: 289-2366 Main Mall, Vancouver, BC
    name: Travel Time to Work
    options:
      mode: transit
  - platform: pocketcasts
    username: tigeroakes@gmail.com
    password: !secret pocketcasts_password
  - platform: steam_online
    api_key: !secret steam_api
    accounts:
      - 76561198074004593
      - 76561198137492282
      - 76561198031616413
      - 76561198210447675
      - 76561198045873121

light:
  - platform: lifx

switch:
  - platform: tplink
    name: Desk Lights
    host: 192.168.50.204

media_player:
  - platform: cast
  - platform: gpmdp
    host: 192.168.50.2

notify:
  - name: web
    platform: html5
    gcm_api_key: !secret gcm_api
    gcm_sender_id: !secret gcm_sender_id
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api

scene:
  - platform: lifx_cloud
    token: !secret lifx_api

tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

ifttt:
  key: !secret ifttt_webhooks

wemo:
  static:
    - 192.168.50.203

hdmi_cec:
  devices:
    TV: 0.0.0.0
    Chromecast: 1.0.0.0
    Pi Zero: 2.0.0.0
    Wii U: 3.0.0.0
    Nintendo Switch: 4.0.0.0

input_select:
  tv_input:
    name: TV Input
    options:
      - Chromecast
      - Wii U
      - Nintendo Switch
    initial: Chromecast
    icon: mdi:television-classic

weblink:
  entities:
    - name: Router
      url: https://router.asus.com:8443
