homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Vancouver
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:


# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: https://home.tigeroakes.com
  ssl_certificate: /config/ssl/fullchain.pem
  ssl_key: /config/ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr
    name: Weather
    monitored_conditions:
      - symbol
      - temperature
      - windSpeed
      - cloudiness
  - platform: steam_online
    api_key: !secret steam_api
    accounts:
      - 76561198074004593
      - 76561198137492282
      - 76561198031616413
      - 76561198210447675
      - 76561198045873121

switch:
  - platform: tplink
    name: Desk Lights
    host: 192.168.50.204
  - platform: tplink
    name: Back Light
    host: 192.168.50.32

asuswrt:
  host: 192.168.50.1
  username: !secret asus_router_username
  password: !secret asus_router_password
  protocol: telnet
  port: 23

device_tracker:
  - platform: asuswrt
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False

notify:
  - platform: html5
    name: HTML5
    gcm_api_key: !secret gcm_api
    gcm_sender_id: !secret gcm_sender_id
  - platform: slack
    name: Slack
    api_key: !secret slack_api
    default_channel: '#general'
    icon: ':house:'

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
